In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ev_charging_patterns[1].csv to ev_charging_patterns[1] (1).csv

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving ev_charging_patterns_cleaned.csv to ev_charging_patterns_cleaned.csv
User uploaded file "ev_charging_patterns_cleaned.csv" with length 369864 bytes

In [ ]:
df['Weekday'] = df['Charging Start Time'].dt.day_name()

df.to_csv('ev_charging_patterns_cleaned.csv', index=False)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_csv('ev_charging_patterns[1] (1).csv')

df.head()

,User ID,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Charging Start Time,Charging End Time,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),Time of Day,Day of Week,State of Charge (Start %),State of Charge (End %),Distance Driven (since last charge) (km),Temperature (°C),Vehicle Age (years),Charger Type,User Type
0,User_1,BMW i3,108.463007,Station_391,Houston,2024-01-01 00:00:00,2024-01-01 00:39:00,60.712346,0.591363,36.389181,13.087717,Evening,Tuesday,29.371576,86.119962,293.602111,27.947953,2.0,DC Fast Charger,Commuter
1,User_2,Hyundai Kona,100.000000,Station_428,San Francisco,2024-01-01 01:00:00,2024-01-01 03:01:00,12.339275,3.133652,30.677735,21.128448,Morning,Monday,10.115778,84.664344,112.112804,14.311026,3.0,Level 1,Casual Driver
2,User_3,Chevy Bolt,75.000000,Station_181,San Francisco,2024-01-01 02:00:00,2024-01-01 04:48:00,19.128876,2.452653,27.513593,35.667270,Morning,Thursday,6.854604,69.917615,71.799253,21.002002,2.0,Level 2,Commuter
3,User_4,Hyundai Kona,50.000000,Station_327,Houston,2024-01-01 03:00:00,2024-01-01 06:42:00,79.457824,1.266431,32.882870,13.036239,Evening,Saturday,83.120003,99.624328,199.577785,38.316313,1.0,Level 1,Long-Distance Traveler
4,User_5,Hyundai Kona,50.000000,Station_108,Los Angeles,2024-01-01 04:00:00,2024-01-01 05:46:00,19.629104,2.019765,10.215712,10.161471,Morning,Saturday,54.258950,63.743786,203.661847,-7.834199,1.0,Level 1,Long-Distance Traveler

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   User ID                                   1320 non-null   object
 1   Vehicle Model                             1320 non-null   object
 2   Battery Capacity (kWh)                    1320 non-null   float64
 3   Charging Station ID                       1320 non-null   object
 4   Charging Station Location                 1320 non-null   object
 5   Charging Start Time                       1320 non-null   object
 6   Charging End Time                         1320 non-null   object
 7   Energy Consumed (kWh)                     1254 non-null   float64
 8   Charging Duration (hours)                 1320 non-null   float64
 9   Charging Rate (kW)                        1254 non-null   float64
 10  Charging Cost (USD)                       1320 non-null   float64
 11  Time of Day                               1320 non-null   object
 12  Day of Week                               1320 non-null   object
 13  State of Charge (Start %)                 1320 non-null   float64
 14  State of Charge (End %)                   1320 non-null   float64
 15  Distance Driven (since last charge) (km)  1254 non-null   float64
 16  Temperature (°C)                          1320 non-null   float64
 17  Vehicle Age (years)                       1320 non-null   float64
 18  Charger Type                              1320 non-null   object
 19  User Type                                 1320 non-null   object
dtypes: float64(10), object(10)
memory usage: 206.4+ KB

In [ ]:
df.isnull().sum()

User ID                                      0
Vehicle Model                                0
Battery Capacity (kWh)                       0
Charging Station ID                          0
Charging Station Location                    0
Charging Start Time                          0
Charging End Time                            0
Energy Consumed (kWh)                       66
Charging Duration (hours)                    0
Charging Rate (kW)                          66
Charging Cost (USD)                          0
Time of Day                                  0
Day of Week                                  0
State of Charge (Start %)                    0
State of Charge (End %)                      0
Distance Driven (since last charge) (km)    66
Temperature (°C)                             0
Vehicle Age (years)                          0
Charger Type                                 0
User Type                                    0
dtype: int64

In [ ]:
df['Energy Consumed (kWh)'].fillna(df['Energy Consumed (kWh)'].median(), inplace=True)

df['Charging Rate (kW)'].fillna(df['Charging Rate (kW)'].median(), inplace=True)

df['Distance Driven (since last charge) (km)'].fillna(
    df['Distance Driven (since last charge) (km)'].median(),
    inplace=True
)

/tmp/ipykernel_3144/1142231988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Energy Consumed (kWh)'].fillna(df['Energy Consumed (kWh)'].median(), inplace=True)
/tmp/ipykernel_3144/1142231988.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Charging Rate (kW)'].fillna(df['Charging Rate (kW)'].median(), inplace=True)
/tmp/ipykernel_3144/1142231988.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Distance Driven (since last charge) (km)'].fillna(

In [ ]:
df.isnull().sum()

User ID                                     0
Vehicle Model                               0
Battery Capacity (kWh)                      0
Charging Station ID                         0
Charging Station Location                   0
Charging Start Time                         0
Charging End Time                           0
Energy Consumed (kWh)                       0
Charging Duration (hours)                   0
Charging Rate (kW)                          0
Charging Cost (USD)                         0
Time of Day                                 0
Day of Week                                 0
State of Charge (Start %)                   0
State of Charge (End %)                     0
Distance Driven (since last charge) (km)    0
Temperature (°C)                            0
Vehicle Age (years)                         0
Charger Type                                0
User Type                                   0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Charging Start Time'] = pd.to_datetime(df['Charging Start Time'])
df['Charging End Time'] = pd.to_datetime(df['Charging End Time'])

In [ ]:
df['Hour'] = df['Charging Start Time'].dt.hour
df['Month'] = df['Charging Start Time'].dt.month
df['Day'] = df['Charging Start Time'].dt.day

In [ ]:
df['Charging Start Time'] = pd.to_datetime(df['Charging Start Time'])
df['Charging End Time'] = pd.to_datetime(df['Charging End Time'])

In [ ]:
import pandas as pd

df = pd.read_csv('/content/ev_charging_patterns_cleaned.csv')

In [ ]:
df['Charging Start Time'] = pd.to_datetime(df['Charging Start Time'])
df['Charging End Time'] = pd.to_datetime(df['Charging End Time'])

In [ ]:
df['Hour'] = df['Charging Start Time'].dt.hour
df['Month'] = df['Charging Start Time'].dt.month
df['Day'] = df['Charging Start Time'].dt.day
df['Weekday'] = df['Charging Start Time'].dt.day_name()

In [ ]:
df.to_csv('ev_charging_patterns_cleaned.csv', index=False)

In [ ]:
df.columns

Index(['User ID', 'Vehicle Model', 'Battery Capacity (kWh)',
       'Charging Station ID', 'Charging Station Location',
       'Charging Start Time', 'Charging End Time', 'Energy Consumed (kWh)',
       'Charging Duration (hours)', 'Charging Rate (kW)',
       'Charging Cost (USD)', 'Time of Day', 'Day of Week',
       'State of Charge (Start %)', 'State of Charge (End %)',
       'Distance Driven (since last charge) (km)', 'Temperature (°C)',
       'Vehicle Age (years)', 'Charger Type', 'User Type', 'Hour', 'Month',
       'Day', 'Weekday'],
      dtype='object')

In [ ]:
from google.colab import files

files.download('ev_charging_patterns_cleaned.csv')